#!/bin/bash

/bin/bash ./List_Databases

echo -n "Enter the name of the database to create tables in: "
read DB_NAME

if [ ! -d "Databases/$DB_NAME" ]; then
    echo "Database '$DB_NAME' does not exist."
    exit 1
fi

if [ "$(whoami)" != "$(stat -c '%U' "Databases/$DB_NAME")" ]; then
    IS_ADMIN=false
    while IFS= read -r admin; do
        if [ "$(whoami)" == "$admin" ]; then
            IS_ADMIN=true
            break
        fi
    done < "admins"

    if [ "$IS_ADMIN" != true ]; then
        echo "Permission denied. You do not have access to create tables in '$DB_NAME'."
        exit 1
    fi
fi

echo -n "Enter the name of the table: "
read TABLE_NAME

echo -n "Enter the number of columns: "
read NUM_COLUMNS

COLUMN_NAMES="ID"

for ((i = 1; i <= NUM_COLUMNS; i++)); do
    echo -n "Enter name for column $i: "
    read COLUMN
    COLUMN_NAMES="$COLUMN_NAMES $COLUMN"
done

echo "$COLUMN_NAMES" > "Databases/$DB_NAME/$TABLE_NAME"
echo "Table '$TABLE_NAME' has been created successfully in database '$DB_NAME'."

## log
LOG_FILE="/opt/logs/db_activity.log"
ADMINS_FILE="./admins"
DB_PATH="./Databases/$DB_NAME"

if grep -qx "$(whoami)" "$ADMINS_FILE"; then
    USER_ROLE="admin"
elif [ "$(stat -c '%U' "$DB_PATH")" = "$(whoami)" ]; then
    USER_ROLE="owner"
else
    USER_ROLE="other"
fi

echo "create Table in:$DB_NAME Table name:$TABLE_NAME  $(whoami):$USER_ROLE $(date)" >> "$LOG_FILE"
