#!/bin/bash

/bin/bash ./List_Databases

echo -n "Enter the name of the database to delete tables from: "
read DB_NAME

if [ ! -d "Databases/$DB_NAME" ]; then
    echo "Database '$DB_NAME' does not exist."
    exit 1
fi

echo "Tables in '$DB_NAME':"
ls "Databases/$DB_NAME"

echo -n "Enter the name of the table to delete: "
read TABLE_NAME

if [ "$(whoami)" != "$(stat -c '%U' "Databases/$DB_NAME")" ]; then
    IS_ADMIN=false
    while IFS= read -r admin; do
        if [ "$(whoami)" == "$admin" ]; then
            IS_ADMIN=true
            break
        fi
    done < "admins"

    if [ "$IS_ADMIN" != true ]; then
        echo "Permission denied. You do not have access to delete tables in '$DB_NAME'."
        exit 1
    fi
fi

if [ ! -f "Databases/$DB_NAME/$TABLE_NAME" ]; then
    echo "Table '$TABLE_NAME' does not exist in database '$DB_NAME'."
    exit 1
fi

rm "Databases/$DB_NAME/$TABLE_NAME"
echo "Table '$TABLE_NAME' has been deleted successfully from database '$DB_NAME'."

## log
LOG_FILE="/opt/logs/db_activity.log"
ADMINS_FILE="./admins"
DB_PATH="./Databases/$DB_NAME"

if grep -qx "$(whoami)" "$ADMINS_FILE"; then
    USER_ROLE="admin"
elif [ "$(stat -c '%U' "$DB_PATH")" = "$(whoami)" ]; then
    USER_ROLE="owner"
else
    USER_ROLE="other"
fi

echo "delete Table:$TABLE_NAME in Database:$DB_NAME $(whoami):$USER_ROLE $(date)" >> "$LOG_FILE"
