#!/bin/bash

backup_type="$1"
database_backup_dir="$2"
rotation_limit=5

if [ ! -d "/opt/Backups/$backup_type/$database_backup_dir" ]; then
    echo "Error: Backup directory '/opt/Backups/$backup_type/$selected_database' not found."
    exit 1
fi


cd "/opt/Backups/$backup_type/$database_backup_dir" || exit

ls -t | tail -n +$((rotation_limit + 1)) | xargs rm -f

echo "Rotation based on database date completed successfully"
