#!/bin/bash

selected_database=$1
compression_mode=$2

if [ ! -d "/opt/Backups/Monthly" ]; then
    mkdir "/opt/Backups/Monthly"
fi
backup_dir="/opt/Backups/Monthly/$selected_database"
database_dir="Databases"

if [ ! -d "$backup_dir" ]; then
    mkdir "$backup_dir"
fi

if [ ! -d "$database_dir/$selected_database" ]; then
    echo "Error: Database directory '$database_dir/$selected_database' not found."
    exit 1
fi

(crontab -l ; echo "0 4 1 * *  bash schedule_backup_monthly $selected_database $compression_mode") | crontab -

current_date=$(date +\%Y\%m\%d)

case "$compression_mode" in
    zip)
        zip -r "$backup_dir/monthly_backup_${selected_database}_$current_date.zip" "$database_dir/$selected_database"
        database_name="monthly_backup_${selected_database}_$current_date.zip"
        echo "Monthly backup for $selected_database completed successfully"
        ;;
    tar)
        tar cf "$backup_dir/monthly_backup_${selected_database}_$current_date.tar" -C "$database_dir" "$selected_database"
        database_name="monthly_backup_${selected_database}_$current_date.tar"
        echo "Monthly backup for $selected_database completed successfully"
        ;;
    gzip)
        tar czf "$backup_dir/monthly_backup_${selected_database}_$current_date.tar.gz" -C "$database_dir" "$selected_database"
        database_name="monthly_backup_${selected_database}_$current_date.tar.gz"
        echo "Monthly backup for $selected_database completed successfully"
        ;;
    *)
        echo "Invalid compression mode selected."
        exit 1
        ;;
esac
/bin/bash "./rotate_backups_by_date" "Monthly" "$database_name"

/bin/bash "./rotate_backups_by_size" "Monthly" "$database_name"
